### ISSUE TITLE
Проблема с сервисным API ключом

### ISSUE THREAD

**Issue by n0madic** [himidori/golang-vk-api#1]
При использовании сервисного токена ваша библиотека падает с ошибкой:
```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/himidori/golang-vk-api.(*VKClient).isTokenValid(0xc0000e82c0, 0x6db5d2, 0x47, 0x0, 0x0)
	/home/nomadic/go/src/github.com/himidori/golang-vk-api/client.go:116 +0x84a
github.com/himidori/golang-vk-api.NewVKClientWithToken(0x6db5d2, 0x47, 0xd0, 0x6a1a60, 0xc000080c01)
	/home/nomadic/go/src/github.com/himidori/golang-vk-api/client.go:73 +0x86
```
Почему-то ВК для сервисного ключа при вызове https://api.vk.com/method/users.get возвращает пустой массив `[]` и вылетает ошибка при попытке получить данные пользователя в https://github.com/himidori/golang-vk-api/blob/master/client.go#L116
Можно это как-то обойти?

Как-то так например
```go
	if len(user) > 0 {
		client.Self.UID = user[0].UID
		client.Self.FirstName = user[0].FirstName
		client.Self.LastName = user[0].LastName
		client.Self.PicSmall = user[0].Photo
		client.Self.PicMedium = user[0].PhotoMedium
		client.Self.PicBig = user[0].PhotoBig
	}
```

**Comment by himidori** [comment]
Добавил структуру TokenOptions, которую опционально можно передать при вызове NewVKClientWithToken, например

```
client, err := NewVKClientWithToken('xxx', &TokenOptions{
	ValidateOnStart: true,
	ServiceToken: true,
})
```

Пробуйте, должно решить проблему

**Comment by n0madic** [comment]
Похоже опять вылезла таже проблема...
```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/himidori/golang-vk-api.(*VKClient).requestSelfID(0xc000200000, 0xc00014ac70, 0xc0001866c8, 0x9be3e0)
	/home/nomadic/go/src/github.com/himidori/golang-vk-api/client.go:199 +0x2f0
github.com/himidori/golang-vk-api.NewVKClientWithToken(0xc000174640, 0x47, 0xc0000f3ca6, 0x5, 0xc000186748, 0xc00015c601)
	/home/nomadic/go/src/github.com/himidori/golang-vk-api/client.go:70 +0x117
```

**Comment by himidori** [comment]
Не могу воспроизвести проблему. У меня работает

**Comment by n0madic** [comment]
пробую самый простой код на текущем мастере
```go
package main

import (
	vkapi "github.com/himidori/golang-vk-api"
)

func main() {
	vkapi.NewVKClientWithToken("...", nil)
}
```
получаю
```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/himidori/golang-vk-api.(*VKClient).requestSelfID(0xc0000e02c0, 0xc00008ec10, 0xc000090bd0, 0xc000090b40)
	/home/nomadic/go/src/github.com/himidori/golang-vk-api/client.go:199 +0x2f0
github.com/himidori/golang-vk-api.NewVKClientWithToken(0x6ab55e, 0x47, 0x0, 0x0, 0xc0000e7f88, 0xc000084058)
	/home/nomadic/go/src/github.com/himidori/golang-vk-api/client.go:70 +0x117
main.main()
	/home/nomadic/github/test/main.go:8 +0x3f
exit status 2
```
на коммите e2be110231d94002ddac26ab4524ea7e0fe36778 все ок...

**Comment by n0madic** [comment]
```go
func (client *VKClient) requestSelfID() (uid int, err error) {
	resp, err := client.makeRequest("users.get", url.Values{})
``` 
возвращает `[]`

Как и прямой запрос 
```
https://api.vk.com/method/users.get?access_token=...&v=5.71
```

**Comment by himidori** [comment]
токен сервисный или обычный юзерский?

**Comment by n0madic** [comment]
токен сервисный, для приложения

**Comment by himidori** [comment]
Так а вы флаг устанавливаете, что это сервисный токен? Функция принимает
TokenOptions, где есть поле ServiceToken

пн, 15 апр. 2019 г., 21:53 Nomadic <notifications@github.com>:

**Comment by n0madic** [comment]
изначальный код моего приложения
```go
		client, err = vkapi.NewVKClientWithToken(token, &vkapi.TokenOptions{
			ValidateOnStart: true,
			ServiceToken:    true,
		})
```
разные комбинации этих параметров никак на ошибку не влияют, потому в примере их опустил..

IsSer**iv**ceToken (sic!) в requestSelfID вроде не участвует

**Comment by himidori** [comment]
Хмм, мне надо получить сервисный токен и потестить самому, чтобы найти
проблему. Есть инструкция как его получить?

пн, 15 апр. 2019 г., 22:06 Nomadic <notifications@github.com>:

**Comment by himidori** [comment]
Если раньше работало, то возможно я принял чей-то кривой пулл реквест,
который это поломал) недавно был один

пн, 15 апр. 2019 г., 22:06 Nomadic <notifications@github.com>:

**Comment by n0madic** [comment]
https://vk.com/dev/service_token
Необходимо здесь добавить приложение https://vk.com/apps?act=manage

Сломалось после этого https://github.com/himidori/golang-vk-api/pull/7

**Comment by himidori** [comment]
исправил проблему, пробуйте. последний пулл реквест действительно убил
проверку, которая была раньше

**Comment by n0madic** [comment]
Теперь все ОК - спасибо!
