### ISSUE TITLE
Ошибка в message.go

### ISSUE THREAD

**Issue by Ekuzkamaza** [himidori/golang-vk-api#10]
`type StickerAttachment struct {

	ID        int    `json:"id"`
	ProductID int    `json:"product_id"`
	Photo64   string `json:"photo_64"`
	Photo128  string `json:"photo_128"`
	Photo256  string `json:'photo_256"`
	Photo352  string `json:"photo_352"`
	Photo512  string `json:"photo_512"`
	Width     int    `json:"width"`
	Height    int    `json:"height"`
}`
вот здесь вместо двойной кавычки одинарная Photo256  string `json:'photo_256"`

**Comment by himidori** [comment]
исправил, спасибо за находку
