### ISSUE TITLE
ошибка при отправке сообщения пользователю

### ISSUE THREAD

**Issue by adatan** [himidori/golang-vk-api#22]
![изображение](https://user-images.githubusercontent.com/50762345/73384100-a1520700-42db-11ea-9445-7697cb9b34a6.png)
![изображение](https://user-images.githubusercontent.com/50762345/73384115-a911ab80-42db-11ea-99cd-c0e7ad8806a5.png)

**Comment by adatan** [comment]
нашёл проблему, вам необходим random_id, я сделал костыль, но вы можете рандомно генерировать его по сиду 
![изображение](https://user-images.githubusercontent.com/50762345/73390309-e16ab700-42e6-11ea-8cc0-bfb0a3df7715.png)

**Comment by adatan** [comment]
А, нет, я ошибся, ничего не получилось:(

**Comment by crossworth** [comment]
This works. Make sure to use a different `random_id ` each time.

Google translate:
Это работает. Убедитесь, что каждый раз используете разные значения `random_id`.


```go
params := url.Values{}
params.Add("random_id", "123")

_, err := client.MessagesSend(msg.UserID, links, params)
if err != nil {
	log.Println(err)
}
```

**Comment by adatan** [comment]
> This works. Make sure to use a different `random_id ` each time.
> 
> Google translate:
> Это работает. Убедитесь, что каждый раз используете разные значения `random_id`.
> 
> ```go
> params := url.Values{}
> params.Add("random_id", "123")
> 
> _, err := client.MessagesSend(msg.UserID, links, params)
> if err != nil {
> 	log.Println(err)
> }
> ```

А вы уверены? Я использую ключ сообщества и пытаюсь отправить сообщение человеку, который в него написал...

**Comment by adatan** [comment]
@crossworth 
![image](https://user-images.githubusercontent.com/50762345/73442904-b6c04300-4366-11ea-9dd3-c33c73cb39ef.png)
not working

**Comment by crossworth** [comment]
I think the problem is with your input, the user id to be precise.

Could you hard code an id and test to see if it works?


Я думаю, что проблема с вашим вводом, точнее идентификатором пользователя.

Не могли бы вы жестко написать код и проверить, работает ли он?


Example:
```go
params := url.Values{}
params.Add("random_id", "123")

_, err := client.MessagesSend(261024452, "test message", params)
if err != nil {
	log.Println(err)
}
```
