### ISSUE TITLE
Как использовать порт?

### ISSUE THREAD

**Issue by ArchieSW** [himidori/golang-vk-api#45]
Написал вк бота с этой либой, запушил в хероку, но он требует забиндить порт (Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch). Может кто помочь?

**Comment by himidori** [comment]
либа не слушает никакой порт, поэтому проблема не в ней

**Comment by Lex4990** [comment]
У тебя в хероку есть переменная окружения PORT по стандарту. В неё кидается порт на котором должно находится твоё приложение. Я не помню зачем, но так устроена работа хероку. В приложении читай эту переменную и запускайся на этом порту.
P.S. Только сейчас увидел, что ответ на вопрос от февраля.
